### ISSUE TITLE
Add the option to print the tar and curl commands instead of running them

### ISSUE THREAD

**Issue by olavfosse** [olav35/0x0#10]
This is useful in multiple situations. It is useful for demonstrating how 0x0 works and to debug the problem in case something went wrong.

The could be implemented as two options.
- `-v` v for verbose. Print the tar and curl commands ran by 
- `-n` n for no execute(feel free to suggest a less bad mnemonic). Don't execute the curl and tar commands(but, still print them if `-v` is used)

**Comment by hardikpnsp** [comment]
I would like to work on this.

**Comment by hardikpnsp** [comment]
@olav35 let me know what you think of the changes made so far.

**Comment by olavfosse** [comment]
Resolved with #11.
